### PR TITLE
Compatibility with Delphi XE6

### PR DESCRIPTION
**Pull request by wlandgraf**
Added support for Delphi XE6

### CODE REVIEW

**Comment by fabioxgn** [comment]
@wlandgraf why not use delphi's `Soap.EncDec` for base64? It is available for X6:

http://stackoverflow.com/a/5795440/727

**Comment by wlandgraf** [comment]
I wanted to avoid any extra dependencies on the code, this helps on package distribution. Also using the same dependencies for all Delphi versions also helps in (my) distribution. So it's more a personal reasons. Nevertheless, Base64 is a rather simple function so this way we have more control over it. I have never used Soap.EncDec unit but after reading a few things about it, I already see some issues with it (see http://stackoverflow.com/questions/5795263/binary-to-base64-delphi) so I think it's safer and easier to add a few lines of code than adding a whole dependency. Do you think it's a bad thing?

**Comment by cesarliws** [comment]
I agree with @wlandgraf, for XE7, XE7.1 and XE8 Delphi has a new implementation in Data.Cloud.CloudAPI, that is not working https://quality.embarcadero.com/browse/RSP-11184 and was fixed only in Seattle. I have to replace it with my own version too for my projects;

**Comment by fabioxgn** [comment]
:+1:

**Comment by paolo-rossi** [comment]
First of all thank you @wlandgraf for your contribution.. 
About the topic library vs code, in general I prefer to use Delphi RTL routines also if they change name/implementation across version but given the bug described by @cesarliws  I think that I'll accept the pull request as it is.

**Pull request merged**
